# Desired linear velocity x in pelvis frame.
# Between [-1, 1] for no to max velocity.
float64 linear_velocity_x

# Desired linear velocity y in pelvis frame.
# Between [-1, 1] for no to max velocity.
float64 linear_velocity_y

# Desired pelvis height above ground in [m].
float64 desired_pelvis_height

# Desired angular velocity around z in pelvis.
# Between [-1, 1] for no to max velocity.
float64 angular_velocity_z
